### ISSUE TITLE
해야할 것

### ISSUE THREAD

**Issue by Hong-YeJi** [lcy061/Mini-project#11]
1. 소스 완성되면 wiki 페이지 소스 영역에 movie.c, main.c 추가하기
2. 결과화면 캡처해서 폴더 만들고 이미지 업로드하기
3. md 페이지 만들기

**Comment by Hong-YeJi** [comment]
함수 구현한 것 내일 중으로 소스 올리시면 제가 확인하고 테스트해보겠습니다!

**Comment by lcy061** [comment]
함수 구현 완료 했습니다.
