### ISSUE TITLE
list 함수 정렬 문제

### ISSUE THREAD

**Issue by lcy061** [lcy061/Mini-project#13]
![image](https://user-images.githubusercontent.com/61354751/117537662-6f326780-b03d-11eb-841f-c4640b81a782.png)

문자의 간격이나 길이마다 일정한 간격을 설정하기 어려워, 
구분선을 통해 구분을 주었습니다. 

혹시 다른 방법이 있을까요?

**Comment by Hong-YeJi** [comment]
괜찮을 것 같습니다!
