### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by Hong-YeJi** [lcy061/Mini-project#2]
- [ ] 역할분담

**홍예지**
[ Main ]  함수
Save 
Load 
Search1 - 이름 검색 
Search3 - 별점 검색
(+ selectMenu)
(+ selectDataNo)

**이찬용**
Create
Read
Update  
Delete
Search2 - 감독 검색
Search4 - 장르 검색  

**together**
- 구조체 정의 : 상의

**각자 맡은 파트**
wiki 
README.md

**Comment by Hong-YeJi** [comment]
void saveData(Movie *s, int count);
int loadData(Movie *s);
void searchMovie(Movie *s, int count);
void searchStar(Movie *s, int count);

**Comment by lcy061** [comment]
void Create(Movie *s, int count)
void Read(Movie *s, int count)
void Update(Movie *s, int num)
void Delete(Movie *s, int num)

void Search2(Movie *s, int count)
void Search4(Movie *s, int count)

**Comment by Hong-YeJi** [comment]
(+ function)
int selectMenu();
int selectDataNo(Movie s[], int count);

**Comment by Hong-YeJi** [comment]
search 함수
void searchDirector(Movie *s, int count);
void searchGenre(Movie *s, int count);
로 함수 이름 변경하였습니다 :)
