### ISSUE TITLE
설계

### ISSUE THREAD

**Issue by lcy061** [lcy061/Mini-project#3]
주제 : 영화 정보

[ 구조체 정의 ] 
- 이름 : char
- 감독 : char 
- 별점 : float
- 장르 : char 
- 개봉일자 : char
- 영화순위 : int

Main 
구조체 배열 변수 : movieList[ ]
현재 생성된 목록 수 : count
최대 배열 수 : maxCount 
선택 메뉴 숫자 : num

void Create(movieList[ ], count)
void Read(movieList[ ], count)
void Update(movieList[ ], num)
void Delete(movieList[ ], num)

Save
Load

Search1
void Search2(movieList[ ], count) 
Search3
void Search4(movieList[ ], count)

**Comment by Hong-YeJi** [comment]
러닝타임 제외하고 데이터를 설정해도 좋을 것 같습니다 :)

**Comment by lcy061** [comment]
void Create(movieList[ ], count)
void Read(movieList[ ], count)
void Update(movieList[ ], num)
void Delete(movieList[ ], num)

void Search2(movieList[ ], count)
void Search4(movieList[ ], count)

Search 함수 void로하고, Read 함수로 출력하는 걸 괜찮을까요?

**Comment by Hong-YeJi** [comment]
넵 괜찮을 것 같습니다!
